name: build encrypted-dns-server

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            target_alias: linux-x86_64
            bin_suffix: ''
            archive_suffix: '.tar.bz2'
    defaults:
      run:
        shell: bash
    env:
      ARCHIVE_PATH: encrypted-dns_${{ github.ref_name }}_${{ matrix.target_alias }}${{ matrix.archive_suffix }}
    # Use a container with GLIBC 2.17
    container: quay.io/pypa/manylinux2014_x86_64

    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=Released on $(date +%Y%m%d%H)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date +%Y%m%d%H)" >> $GITHUB_ENV

      - name: Show GLIBC
        run: ldd --version

      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: DNSCrypt/encrypted-dns-server
          ref: master

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          default: true
          override: true
          profile: minimal

      - name: Prepare build
        run: |
          echo 'lto = "fat"' >> Cargo.toml

      - name: Build
        uses: actions-rs/cargo@v1
        env:
          RUSTFLAGS: "-C strip=symbols"
        with:
          command: build
          args: --release

      - name: Prepare archive
        run: |
          mkdir encrypted-dns
          cp target/release/encrypted-dns${{ matrix.bin_suffix }} encrypted-dns/
          cp README.md example-encrypted-dns.toml encrypted-dns/
          tar cvjpf ${ARCHIVE_PATH} encrypted-dns

      - name: Store archive
        uses: actions/upload-artifact@v3
        with:
          name: encrypted-dns_${{ matrix.target_alias }}
          path: ${{ env.ARCHIVE_PATH }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          files: |
            encrypted-dns_*.tar.bz2
